# Generated by Django 5.2.10 on 2026-01-21 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('priority', models.IntegerField(default=1, help_text='Wyższy numer = ważniejsza reguła')),
                ('is_active', models.BooleanField(default=True)),
                ('conditions', models.JSONField(blank=True, default=list, help_text='Lista warunków jako JSON')),
                ('action', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'W trakcie'), ('success', 'Sukces'), ('failed', 'Błąd')], default='running', max_length=20)),
                ('action', models.CharField(blank=True, help_text='Wykonana akcja', max_length=255)),
                ('affected_devices_count', models.IntegerField(default=0, help_text='Liczba urządzeń, na które wpłynęła operacja')),
                ('message', models.TextField(blank=True, help_text='Opis operacji lub błąd')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Dodatkowe szczegóły operacji')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimization.optimizationrule')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField(blank=True, help_text='Np. docelowa temperatura lub jasność', null=True)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='simulation.deviceconfig')),
            ],
        ),
    ]
