# Generated by Django 5.2.10 on 2026-01-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0002_remove_userpreference_device_and_more'),
        ('optimization', '0003_optimization_log'),
    ]

    operations = [
    ]
