# Generated by GitHub Copilot on 2026-01-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0004_merge_20260121_0102'),
        ('simulation', '0005_alter_deviceconfig_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='target_value',
            field=models.FloatField(blank=True, help_text='Np. docelowa temperatura lub jasność', null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='device',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='preference',
                to='simulation.deviceconfig',
            ),
        ),
    ]
