# Generated by Django 5.2.10 on 2026-01-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0005_restore_userpreference_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationlog',
            name='action',
            field=models.CharField(blank=True, help_text='Wykonana akcja', max_length=255),
        ),
    ]
