# Generated by Django 5.2.10 on 2026-01-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_alert_details_alert_measurement_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeltype',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email')], max_length=20, unique=True),
        ),
    ]
