# Generated by Django 5.2.10 on 2026-01-21 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_millis_per_tick', models.PositiveIntegerField(default=6000)),
                ('simulated_millis_per_tick', models.PositiveIntegerField(default=100)),
                ('consumption_mode', models.CharField(default='normal', max_length=50)),
                ('charging_mode', models.CharField(default='balanced', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('outside', 'Outside'), ('inside', 'Inside')], max_length=20)),
                ('temperature_c', models.FloatField(default=20.0)),
                ('sunlight', models.FloatField(default=0.5)),
                ('brightness', models.FloatField(default=0.5)),
                ('cloudiness', models.FloatField(default=0.3)),
                ('wind_speed', models.FloatField(default=2.0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('outside_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inside_weathers', to='simulation.weatherconfig')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weathers', to='simulation.simulationconfig')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('lighting', 'Lighting'), ('airconditioning', 'Air Conditioning'), ('photovoltaic', 'Photovoltaic'), ('energystorage', 'Energy Storage'), ('electricgrid', 'Electric Grid'), ('heating', 'Heating System'), ('windturbine', 'Wind Turbine')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('initial_level', models.FloatField(blank=True, null=True)),
                ('initial_is_on', models.BooleanField(default=True)),
                ('power_watts', models.FloatField(blank=True, null=True)),
                ('light_output', models.FloatField(blank=True, null=True)),
                ('cooling_power', models.FloatField(blank=True, null=True)),
                ('peak_power', models.FloatField(blank=True, null=True)),
                ('capacity_wh', models.FloatField(blank=True, null=True)),
                ('max_charge_w', models.FloatField(blank=True, null=True)),
                ('max_discharge_w', models.FloatField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='simulation.simulationconfig')),
                ('weather_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='simulation.weatherconfig')),
            ],
        ),
    ]
