# Generated by Django 5.2.10 on 2026-01-20 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0002_remove_userpreference_device_and_more'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('lighting', 'lighting'), ('airconditioning', 'airconditioning'), ('photovoltaic', 'photovoltaic'), ('energystorage', 'energystorage')], max_length=30)),
                ('weather_ref', models.UUIDField()),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('outside', 'outside'), ('inside', 'inside')], max_length=20)),
                ('outside_ref', models.UUIDField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weathers', to='simulation.simulationconfig')),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='EnergyTariff',
        ),
        migrations.DeleteModel(
            name='SimulationState',
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='simulation.simulationconfig'),
        ),
    ]
