# Generated by Django 5.2.10 on 2026-01-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_deviceconfig_simulationconfig_weatherconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='capacity_wh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='cooling_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='initial_is_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='initial_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='light_output',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='max_charge_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='max_discharge_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='peak_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='power_watts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='base_millis_per_tick',
            field=models.PositiveIntegerField(default=900000),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='charging_mode',
            field=models.CharField(default='balanced', max_length=50),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='consumption_mode',
            field=models.CharField(default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='simulated_millis_per_tick',
            field=models.PositiveIntegerField(default=30000),
        ),
        migrations.AddField(
            model_name='weatherconfig',
            name='brightness',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='weatherconfig',
            name='cloudiness',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='weatherconfig',
            name='sunlight',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='weatherconfig',
            name='temperature_c',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='weatherconfig',
            name='wind_speed',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='type',
            field=models.CharField(choices=[('lighting', 'Lighting'), ('airconditioning', 'Air Conditioning'), ('photovoltaic', 'Photovoltaic'), ('energystorage', 'Energy Storage')], max_length=30),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='weather_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='simulation.weatherconfig'),
        ),
        migrations.AlterField(
            model_name='weatherconfig',
            name='outside_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inside_weathers', to='simulation.weatherconfig'),
        ),
        migrations.AlterField(
            model_name='weatherconfig',
            name='type',
            field=models.CharField(choices=[('outside', 'Outside'), ('inside', 'Inside')], max_length=20),
        ),
    ]
