# Generated by Django 5.2.10 on 2026-01-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_deviceconfig_capacity_wh_deviceconfig_cooling_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationconfig',
            name='simulated_millis_per_tick',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
