# Generated by Django 5.2.10 on 2026-01-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_alter_simulationconfig_simulated_millis_per_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfig',
            name='type',
            field=models.CharField(choices=[('lighting', 'Lighting'), ('airconditioning', 'Air Conditioning'), ('photovoltaic', 'Photovoltaic'), ('energystorage', 'Energy Storage'), ('electricgrid', 'Electric Grid'), ('heating', 'Heating System'), ('windturbine', 'Wind Turbine')], max_length=30),
        ),
    ]
