# Generated by Django 5.2.10 on 2026-01-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_alter_deviceconfig_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationconfig',
            name='base_millis_per_tick',
            field=models.PositiveIntegerField(default=3600000),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='simulated_millis_per_tick',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
