# Generated by Django 5.2.10 on 2026-01-19 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodStart', models.DateTimeField()),
                ('periodEnd', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('reportType', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SEASONAL', 'Seasonal'), ('SEMIANNUAL', 'Semiannual'), ('ANNUAL', 'Annual')], db_index=True, default='DAILY', max_length=20)),
                ('metric', models.CharField(blank=True, choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('energy', 'Energy'), ('power', 'Power'), ('voltage', 'Voltage')], db_index=True, max_length=30, null=True)),
                ('roomId', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('fileType', models.CharField(choices=[('PDF', 'Pdf'), ('PNG', 'Png')], db_index=True, default='PDF', max_length=10)),
                ('fileContent', models.BinaryField()),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
