# Generated by Django 5.2.10 on 2026-01-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_statisticelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticelement',
            name='metric',
            field=models.CharField(blank=True, choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('energy', 'Energy'), ('power', 'Power'), ('voltage', 'Voltage'), ('sunlight', 'Sunlight'), ('brightness', 'Brightness'), ('cloudiness', 'Cloudiness'), ('rainfall', 'Rainfall'), ('wind', 'Wind')], db_index=True, max_length=30, null=True),
        ),
    ]
