# Generated by Django 5.2.9 on 2025-12-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Panel Sterowania',
                'verbose_name_plural': 'Panel Sterowania',
                'managed': False,
            },
        ),
    ]
