# Generated by Django 5.2.10 on 2026-01-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_variable', models.CharField(max_length=50)),
                ('model_uuid', models.UUIDField(unique=True)),
                ('binary_data', models.BinaryField(help_text='Zserializowany obiekt modelu (.pkl)')),
                ('mape_result', models.FloatField(help_text='Wynik błędu MAPE uzyskanego podczas walidacji')),
                ('is_active', models.BooleanField(default=False, help_text='Czy ten model jest obecnie używany do prognoz?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
