# Generated by Django 5.2.10 on 2026-01-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_trainedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='mape_result',
            field=models.FloatField(help_text='Wynik błędu MAPE'),
        ),
    ]
