# Generated by Django 5.2.10 on 2026-01-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0003_alter_trainedmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prognoza', 'verbose_name_plural': 'Prognozy'},
        ),
        migrations.AlterModelOptions(
            name='trainedmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wytrenowany Model', 'verbose_name_plural': 'Wytrenowane Modele'},
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='binary_data',
            field=models.BinaryField(help_text='Zserializowany obiekt klasy PredictionModel (.pkl)'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Czy model jest aktualnie używany do prognoz?'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='mape_result',
            field=models.FloatField(help_text='Wynik błędu MAPE modelu'),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='target_variable',
            field=models.CharField(help_text='consumption lub production', max_length=50),
        ),
    ]
