# Generated by Django 5.2.10 on 2026-01-21 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0004_alter_forecast_options_alter_trainedmodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainedModel',
        ),
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['-created_at']},
        ),
    ]
